# Color variable shortcuts
export COLOR_DARK_RED='\[\e[0;31m\]'
export COLOR_RED='\[\e[1;31m\]'
export COLOR_DARK_GREEN='\[\e[0;32m\]'
export COLOR_GREEN='\[\e[1;32m\]'
export COLOR_DARK_YELLOW='\[\e[0;33m\]'
export COLOR_YELLOW='\[\e[1;33m\]'
export COLOR_DARK_BLUE='\[\e[0;34m\]'
export COLOR_BLUE='\[\e[1;34m\]'
export COLOR_DARK_MAGENTA='\[\e[0;35m\]'
export COLOR_MAGENTA='\[\e[1;35m\]'
export COLOR_DARK_CYAN='\[\e[0;36m\]'
export COLOR_CYAN='\[\e[1;36m\]'
export COLOR_GRAY='\[\e[0;37m\]'
export COLOR_WHITE='\[\e[1;37m\]'
export COLOR_NORM='\[\e[m\]'
