#!/bin/sh

#
####    ptheme default theme    ####
#
# Here is the default theme. It
# includes your username, hostname,
# working directory, and the return
# status of the last command, if
# it's something other than 0.
#
# ##  NOTICE  ##
# This script will run every time
# you hit enter, so just remember
# that when you add extra functions
# and notice that it's slowing down.
# ##  ######  ##
#
####    ####################    ####
#

# Save the return value of the last command
RET="$1"

# Make an error message (to add spacing to error code)
ERROR=""
if [ "$RET" != "0" ]; then
	ERROR="$RET "
fi

# Color shortcut variables
RED='\[\e[1;31m\]'
GREEN='\[\e[1;32m\]'
CYAN='\[\e[1;36m\]'
DARK_CYAN='\[\e[0;36m\]'
WHITE='\[\e[1;37m\]'
NORM='\[\e[m\]'

echo "${CYAN}\u \
${DARK_CYAN}\h \
${GREEN}\w \
${RED}${ERROR}\
${WHITE}\$ ${NORM}"
