#!/bin/sh

# Save the return value of the last command
RET="$1"

# Color shortcut variables
RED='\[\e[1;31m\]'
GREEN='\[\e[1;32m\]'
CYAN='\[\e[1;36m\]'
DARK_CYAN='\[\e[0;36m\]'
WHITE='\[\e[1;37m\]'
NORM='\[\e[m\]'

echo "${CYAN}\u ${DARK_CYAN}\h ${GREEN}\w ${RED}${RET} ${WHITE}$ ${NORM}"
