#!/bin/sh

# Config {{{

# Save the return value of the last command
RET="$1"

# Get rid of ret if it's 0
if [ "$RET" = "0" ]; then
	RET=""
fi

# Update path to include folder with necessary prompt scripts
# NOTE: This doesn't update the path outside this script
PATH="$PATH:$PROMPT_BASE_DIR/bin"

# }}}

# Shortcut variables {{{

# Color shortcut variables
GRAY='\[\e[1;30m\]'
RED='\[\e[1;31m\]'
DARK_RED='\[\e[0;31m\]'
DARK_GREEN='\[\e[0;32m\]'
GREEN='\[\e[1;32m\]'
YELLOW='\[\e[1;33m\]'
DARK_YELLOW='\[\e[-;33m\]'
BLUE='\[\e[1;34m\]'
DARK_BLUE='\[\e[0;34m\]'
DARK_MAGENTA='\[\e[0;35m\]'
MAGENTA='\[\e[1;35m\]'
DARK_CYAN='\[\e[0;36m\]'
CYAN='\[\e[1;36m\]'
WHITE='\[\e[1;37m\]'
NORM='\[\e[m\]'

# }}}

# Prompt variables {{{

# Strings for the date command
# Must be defined after the color variables
DATE_STR="${CYAN}%a ${DARK_CYAN}%b %d"
TIME_STR=" ${BLUE}%r"

# Get git info for my prompt
GIT_BRANCH=$(git_prompt_lite.sh)

# Modify git branch
if [ -n "$GIT_BRANCH" ]; then
	GIT_BRANCH="${WHITE}: ${DARK_GREEN}${GIT_BRANCH}"
fi

# }}}

echo "\n\
$(date "+${DATE_STR}${TIME_STR}")\
\n${YELLOW}[\
${MAGENTA}\u${WHITE}@${DARK_MAGENTA}\h\
${YELLOW}] ${WHITE}-> \
${GREEN}\w${DARK_GREEN}${GIT_BRANCH}\
\n${RED}${RET} ${WHITE}$ ${NORM}"

# vim: foldmethod=marker foldmarker={{{,}}}
