#!/bin/sh

# Config {{{

# Update path to include folder with necessary prompt scripts
# NOTE: This doesn't update the path outside this script
PATH="$PATH:$PTHEME_BASE_DIR/bin"

# Variables for the date and time
DATE_STR="${COLOR_CYAN}%a ${COLOR_DARK_CYAN}%b %d"
TIME_STR=" ${COLOR_BLUE}%r"

# Block colors
USER_COLOR="$COLOR_MAGENTA"
HOST_COLOR="$COLOR_DARK_MAGENTA"
DIRECTORY_COLOR="$COLOR_GREEN"
RETURN_STATUS_COLOR="$COLOR_RED"
PROMPT_COLOR="$COLOR_WHITE"

# }}}

# Prompt variables {{{

# Strings for the date command
TIME_BLOCK="$(date "+${DATE_STR}${TIME_STR}")"

# Network status as the @ sign
NETWORK_BLOCK_COLOR="$(network_status_color.sh)"
NETWORK_BLOCK="${NETWORK_BLOCK_COLOR}@"

# Get battery percentage and status
BATTERY_PERCENT="$(battery_percent.sh)"
if [ -n "$BATTERY_PERCENT" ]; then
	BATTERY_PERCENT_COLOR="\[$(battery_percent_color.sh ${BATTERY_PERCENT})\]"
	BATTERY_BLOCK="${COLOR_WHITE}:${BATTERY_PERCENT_COLOR}${BATTERY_PERCENT}%"
fi

# Get git info for my prompt
eval "$(git_prompt.sh -b -c)"
if [ -n "$GIT_PROMPT_STATUS" ]; then
	GIT_BLOCK="${COLOR_WHITE}: \[${GIT_PROMPT_COLOR}\]${GIT_PROMPT_BRANCH}"
fi

# Return status block, only if the value is non-zero
if [ "$RETURN_STATUS" != "0" ]; then
	RETURN_STATUS_BLOCK=" ${RETURN_STATUS_COLOR}${RETURN_STATUS}"
fi

# }}}

echo "\n${TIME_BLOCK}\n\
${COLOR_YELLOW}[\
${USER_COLOR}\u${NETWORK_BLOCK}${HOST_COLOR}\h${BATTERY_BLOCK}\
${COLOR_YELLOW}]\
${COLOR_WHITE} -> ${DIRECTORY_COLOR}\w${GIT_BLOCK}\n\
${RETURN_STATUS_BLOCK} ${PROMPT_COLOR}\$ ${COLOR_NORM}"

# vim: foldmethod=marker foldmarker={{{,}}}
