#!/bin/sh

# Config {{{

# Save the return value of the last command
RET="$1"

# Get rid of ret if it's 0
if [ "$RET" = "0" ]; then
	RET=""
fi

# Update path to include folder with necessary prompt scripts
# NOTE: This doesn't update the path outside this script
PATH="$PATH:$PROMPT_BASE_DIR/bin"

# }}}

# Shortcut variables {{{

# Color shortcut variables
GRAY='\[\e[1;30m\]'
RED='\[\e[1;31m\]'
DARK_RED='\[\e[0;31m\]'
DARK_GREEN='\[\e[0;32m\]'
GREEN='\[\e[1;32m\]'
YELLOW='\[\e[1;33m\]'
DARK_YELLOW='\[\e[-;33m\]'
BLUE='\[\e[1;34m\]'
DARK_BLUE='\[\e[0;34m\]'
DARK_MAGENTA='\[\e[0;35m\]'
MAGENTA='\[\e[1;35m\]'
DARK_CYAN='\[\e[0;36m\]'
CYAN='\[\e[1;36m\]'
WHITE='\[\e[1;37m\]'
NORM='\[\e[m\]'

# }}}

# Prompt variables {{{

# Strings for the date command
# Must be defined after the color variables
DATE_STR="${CYAN}%a ${DARK_CYAN}%b %d"
TIME_STR=" ${BLUE}%r"

# Network status as the @ sign
NETWORK_PROMPT_COLOR="$(network_status_color.sh)"
NETWORK_PROMPT="${NETWORK_PROMPT_COLOR}@${NORM}"

# Get battery percentage and status
BATTERY_PROMPT="$(battery_percent.sh)"
if [ -n "$BATTERY_PROMPT" ]; then
	BATTERY_PROMPT_COLOR="\[$(battery_percent_color.sh ${BATTERY_PROMPT})\]"
	BATTERY_PROMPT="${WHITE}:${BATTERY_PROMPT_COLOR}${BATTERY_PROMPT}%${NORM}"
fi

# Get git info for my prompt
eval "$(git_prompt.sh -b -c)"
if [ -n "$GIT_PROMPT_STATUS" ]; then
	GIT_PROMPT="${WHITE}: ${GIT_PROMPT_COLOR}${GIT_PROMPT_BRANCH}${NORM}"
fi

# }}}

echo "\n\n\
$(date "+${DATE_STR}${TIME_STR}")\
\n${YELLOW}[\
${MAGENTA}\u${WHITE}\
${NETWORK_PROMPT}\
${DARK_MAGENTA}\h\
${BATTERY_PROMPT}\
${YELLOW}]\
${WHITE} -> \
${GREEN}\w${GIT_PROMPT}\
${NORM}\n${RED}${RET} ${WHITE}$ ${NORM}"

# vim: foldmethod=marker foldmarker={{{,}}}
