#!/bin/sh

# A reminder of what the original PS1 looked like
#PS1="\n\[\033[1;37m\]\342\224\214($(if [[ ${EUID} == 0 ]]; then echo '$bold${red}\u'; else echo '$bold${green}\u'; fi)\[\033[1;37m\])\342\224\200(\[\033[1;34m\]\#\[\033[1;37m\])\342\224\200(\[\033[1;33m\]\@ \d\[\033[1;37m\])\[\033[1;37m\]\n\342\224\224\342\224\200(\[\033[1;32m\]\w\[\033[1;37m\])\342\224\200(\[\033[1;32m\]\$(ls -1 | wc -l | sed 's: ::g') files, \$(ls -lah | grep -m 1 total | sed 's/total //')b\[\033[1;37m\])\342\224\200> \[\033[0m\]"

# Config {{{

# Save the exit value of the last command (comes in as $1)
RET="$1"

# Update path to include folder with necessary prompt scripts
# NOTE: This doesn't update the path outside this script
PATH="$PATH:$PROMPT_BASE_DIR/bin"

# String for the time
TIME_STRING="%a, %b %d %r"

# Color for box characters
BOX_COLOR="$COLOR_WHITE"

# Block colors
USER_COLOR="$COLOR_CYAN"
TIME_COLOR="$COLOR_BLUE"
RETURN_STATUS_COLOR="$COLOR_RED"
REBOOT_COLOR="\[\e[1;5;31m\]"
DIRECTORY_COLOR="$COLOR_GREEN"
PROMPT_COLOR="$COLOR_CYAN"

# Source box printing plugin to get box characters with their color
source "$PROMPT_PLUGINS_DIR/box.sh"

# }}}

# Prompt variables {{{

# User block
USER_BLOCK="${BOX_TOPL}[${USER_COLOR}\u${BOX_COLOR}]"

# Time and color
TIME="${TIME_COLOR}$(date "+${TIME_STRING}")"
TIME_BLOCK="${BOX_HORIZ}(${TIME}${BOX_COLOR})"

# Get battery percentage and status
BATTERY_PERCENT="$(battery_percent.sh)"
if [ -n "$BATTERY_PERCENT" ]; then
	BATTERY_PERCENT_COLOR="\[$(battery_percent_color.sh ${BATTERY_PERCENT})\]"
	BATTERY_BLOCK="${BATTERY_PERCENT_COLOR}${BATTERY_PERCENT}%"
	BATTERY_BLOCK="${BOX_HORIZ}(${BATTERY_BLOCK}${BOX_COLOR})"
fi

# Return status block, only if the value exists and is non-zero
if [ -n "$RET" ] && [ "$RET" != "0" ]; then
	RETURN_STATUS_BLOCK="${BOX_HORIZ}[${RETURN_STATUS_COLOR}${RET}${BOX_COLOR}]"
fi

# Check to see if I need to reboot to finish kernel update
if check_kernel_behind.sh; then
	REBOOT_BLOCK="${BOX_HORIZ}(${REBOOT_COLOR}Reboot!${COLOR_NORM}${BOX_COLOR})"
fi

# Git info
eval "$(git_prompt.sh -b -c)"
if [ -n "$GIT_PROMPT_STATUS" ]; then
	GIT_BLOCK="${COLOR_WHITE}->\[${GIT_PROMPT_COLOR}\]${GIT_PROMPT_BRANCH}"
fi

# Directory block
DIRECTORY_BLOCK="${BOX_HORIZ}(${DIRECTORY_COLOR}\w${GIT_BLOCK}${BOX_COLOR})"

# Prompt block
PROMPT_BLOCK="${BOX_HORIZ}(${PROMPT_COLOR}\$${BOX_COLOR}>"

# }}}

echo "\n$USER_BLOCK\
${TIME_BLOCK}\
${BATTERY_BLOCK}\
${RETURN_STATUS_BLOCK}\
${REBOOT_BLOCK}\
\n${BOX_BOTL}\
${DIRECTORY_BLOCK}\
${PROMPT_BLOCK} ${COLOR_NORM}"

# vim: foldmethod=marker foldmarker={{{,}}}
