#!/bin/sh

# Config {{{

# Save the exit value of the last command
RET="$1"

# Update path to include folder with necessary prompt scripts
# NOTE: This doesn't update the path outside this script
PATH="$PATH:$PROMPT_BASE_DIR/bin"

# }}}

# Shortcut variables {{{

# Color shortcut variables
RED='\[\e[1;31m\]'
GREEN='\[\e[1;32m\]'
BLUE='\[\e[1;34m\]'
CYAN='\[\e[1;36m\]'
WHITE='\[\e[1;37m\]'
NORM='\[\e[m\]'

# Box printing shortcut variables
BOX_TOPL='\342\224\214'
BOX_BOTL='\342\224\224'
BOX_HORIZ='\342\224\200'

# }}}

# Get git information
eval "$(git_prompt.sh -b -c)"
if [ -n "$GIT_PROMPT_STATUS" ]; then
	GIT_PROMPT="${WHITE}->\[${GIT_PROMPT_COLOR}\]${GIT_PROMPT_BRANCH}"
fi

# Variable for the time
TIME_PROMPT="${BLUE}$(date "+%H:%M:%S")"

echo "${WHITE}${BOX_TOPL}[${CYAN}\u@\h${WHITE}]\
${BOX_HORIZ}(${GREEN}\w${GIT_PROMPT}${WHITE})\
${BOX_HORIZ}(${TIME_PROMPT}${WHITE})\
${NORM}\n${WHITE}${BOX_BOTL}${BOX_HORIZ}(${CYAN}\$${WHITE}> ${NORM}"

# vim: foldmethod=marker foldmarker={{{,}}}
