#!/bin/sh

# Config {{{

# Save the exit value of the last command
RET="$1"

# Update path to include folder with necessary prompt scripts
# NOTE: This doesn't update the path outside this script
PATH="$PATH:$PROMPT_BASE_DIR/bin"

# String for the time
TIME_STRING="%H:%M:%S"

# Color for box characters
BOX_COLOR="$COLOR_WHITE"

# Block colors
USER_HOST_COLOR="$COLOR_CYAN"
DIRECTORY_COLOR="$COLOR_GREEN"
TIME_COLOR="$COLOR_BLUE"
RETURN_STATUS_COLOR="$COLOR_RED"
PROMPT_COLOR="$COLOR_CYAN"

# Source box printing plugin to get box characters with their color
. "$PROMPT_PLUGINS_DIR/box.sh"

# }}}

# Prompt variables {{{

# User and hostname
USER_HOST_BLOCK="${BOX_TOPL}[${USER_HOST_COLOR}\u@\h${BOX_COLOR}]"

# Get git information
eval "$(git_prompt.sh -b -c)"
if [ -n "$GIT_PROMPT_STATUS" ]; then
	GIT_BLOCK="${COLOR_WHITE}->\[${GIT_PROMPT_COLOR}\]${GIT_PROMPT_BRANCH}"
fi

# Directory block
DIRECTORY_BLOCK="${BOX_HORIZ}(${DIRECTORY_COLOR}\w${GIT_BLOCK}${BOX_COLOR})"

# Variable for the time
TIME="${TIME_COLOR}$(date "+${TIME_STRING}")"
TIME_BLOCK="${BOX_HORIZ}(${TIME}${BOX_COLOR})"

# Return status block, only if it exists and is non-zero
if [ -n "$RET" ] && [ "$RET" != "0" ]; then
	RETURN_STATUS_BLOCK="${BOX_HORIZ}[${RETURN_STATUS_COLOR}${RET}${BOX_COLOR}]"
fi

# Prompt character block
PROMPT_BLOCK="${BOX_HORIZ}(${PROMPT_COLOR}\$${BOX_COLOR}>"

# }}}

echo "${USER_HOST_BLOCK}\
${DIRECTORY_BLOCK}\
${TIME_BLOCK}\
\n${BOX_BOTL}\
${RETURN_STATUS_BLOCK}\
${PROMPT_BLOCK} ${COLOR_NORM}"

# vim: foldmethod=marker foldmarker={{{,}}}
