#!/bin/sh

# Startup config {{{

# Save the exit value of the last command (comes in as $1)
RET="$1"

# Update path to include folder with necessary prompt scripts
# NOTE: This doesn't update the path outside this script
PATH="$PATH:$PROMPT_BASE_DIR/bin"

# }}}

# Variables {{{

# Shortcut variables {{{

# Color shortcut variables
RED='\[\e[1;31m\]'
GREEN='\[\e[1;32m\]'
BLUE='\[\e[1;34m\]'
CYAN='\[\e[1;36m\]'
WHITE='\[\e[1;37m\]'
NORM='\[\e[m\]'

# Box printing shortcut variables
BOX_TOPL='\342\224\214'
BOX_BOTL='\342\224\224'
BOX_HORIZ='\342\224\200'

# }}}

# Network status
NETWORK_STATUS_COLOR="\[$(network_status_color.sh)\]"
NETWORK_STATUS="${NETWORK_STATUS_COLOR}@"

# Git info
eval "$(git_prompt.sh -b -c)"
if [ -n "$GIT_PROMPT_STATUS" ]; then
	GIT_PROMPT="${WHITE}->${GIT_PROMPT_COLOR}${GIT_PROMPT_BRANCH}${NORM}"
fi

# Get battery percentage and status
BATTERY_PROMPT="$(battery_percent.sh)"
if [ -n "$BATTERY_PROMPT" ]; then
	BATTERY_PROMPT_COLOR="\[$(battery_percent_color.sh ${BATTERY_PROMPT})\]"
	BATTERY_PROMPT="${BATTERY_PROMPT_COLOR}${BATTERY_PROMPT}%${NORM}"
fi

# Time and color
TIME_COLOR="$BLUE"
TIME="${TIME_COLOR}$(date '+%H:%M:%S')"

# Check to see if I need to reboot to finish kernel update
if check_kernel_behind.sh; then
	REBOOT_CHECK="${WHITE}${BOX_HORIZ}(\[\e[1;5;31m\]Reboot!\[\e[0;1;37m\])${NORM}"
fi

# }}}

echo "${WHITE}${BOX_TOPL}[${CYAN}\u\
${NETWORK_STATUS}\
${CYAN}\h${WHITE}]\
${BOX_HORIZ}(${GREEN}\w${GIT_PROMPT}${WHITE})\
${BOX_HORIZ}(${BATTERY_PROMPT}${WHITE})\
${BOX_HORIZ}(${TIME}${WHITE})\
${BOX_HORIZ}[${RED}${RET}${WHITE}]\
${REBOOT_CHECK}\
${NORM}\n "
#${NORM}\n${WHITE}${BOX_BOTL}${BOX_HORIZ}(${CYAN}\$${WHITE}> ${NORM}"

# vim: foldmethod=marker foldmarker={{{,}}}
