#!/bin/sh

# Config {{{

# Update path to include folder with necessary prompt scripts
# NOTE: This doesn't update the path outside this script
PATH="$PATH:$PTHEME_BASE_DIR/bin"

# String for the time
TIME_STRING="%H:%M:%S"

# Color for box characters
[ -z "$BOX_COLOR" ] && BOX_COLOR="$COLOR_WHITE"

# Block colors
USER_COLOR="$COLOR_CYAN"
HOST_COLOR="$COLOR_CYAN"
DIRECTORY_COLOR="$COLOR_GREEN"
TIME_COLOR="$COLOR_BLUE"
RETURN_STATUS_COLOR="$COLOR_RED"
REBOOT_COLOR="\[\e[1;5;31m\]"

# Source box printing plugin to get box characters with their color
. "$PTHEME_PLUGINS_DIR/box.sh"

# }}}

# Prompt variables {{{

# Network status
NETWORK_BLOCK_COLOR="\[$(network_status_color.sh)\]"
NETWORK_BLOCK="${NETWORK_BLOCK_COLOR}@"

# Git info
eval "$(git_prompt.sh -b -c)"
if [ -n "$GIT_PROMPT_STATUS" ]; then
	GIT_BLOCK="${COLOR_WHITE}->\[${GIT_PROMPT_COLOR}\]${GIT_PROMPT_BRANCH}"
fi

# Directory and git info
DIRECTORY_BLOCK="${BOX_HORIZ}(${DIRECTORY_COLOR}\w${GIT_BLOCK}${BOX_COLOR})"

# Get battery percentage and status
BATTERY_PERCENT="$(battery_percent.sh)"
if [ -n "$BATTERY_PERCENT" ]; then
	BATTERY_PERCENT_COLOR="\[$(battery_percent_color.sh ${BATTERY_PERCENT})\]"
	BATTERY_PERCENT="${BATTERY_PERCENT_COLOR}${BATTERY_PERCENT}%"
	BATTERY_BLOCK="${BOX_HORIZ}(${BATTERY_PERCENT}${BOX_COLOR})"
fi

# Time and color
TIME="${TIME_COLOR}$(date "+${TIME_STRING}")"
TIME_BLOCK="${BOX_HORIZ}(${TIME}${BOX_COLOR})"

# Return status block, only if the value is non-zero
if [ "$RETURN_STATUS" != "0" ]; then
	RETURN_STATUS_BLOCK="${BOX_HORIZ}[${RETURN_STATUS_COLOR}${RETURN_STATUS}${BOX_COLOR}]"
fi

# Check to see if I need to reboot to finish kernel update
if check_kernel_behind.sh; then
	REBOOT_BLOCK="${BOX_HORIZ}(${REBOOT_COLOR}Reboot!${COLOR_NORM}${BOX_COLOR})"
fi

# }}}

echo "${BOX_TOPL}[${USER_COLOR}\u\
${NETWORK_BLOCK}\
${HOST_COLOR}\h${BOX_COLOR}]\
${DIRECTORY_BLOCK}\
${BATTERY_BLOCK}\
${TIME_BLOCK}\
${RETURN_STATUS_BLOCK}\
${REBOOT_BLOCK}\
${COLOR_NORM}\n "
#\n${BOX_BOTL}${BOX_HORIZ}(${COLOR_CYAN}\$${BOX_COLOR}> ${COLOR_NORM}"

# vim: foldmethod=marker foldmarker={{{,}}}
