#!/bin/sh

# Config {{{

# String for the date command
DATE_SEQ="+%I:%M:%S %p"

# Save the exit value of the last command (comes in as $1)
RET="$1"

# Update path to include folder with necessary prompt scripts
# NOTE: This doesn't update the path outside this script
PATH="$PATH:$PROMPT_BASE_DIR/bin"

# Setting up the git branch
GIT_BRANCH=$(git_prompt.sh)

# }}}

# Shortcut variables {{{

# Color shortcut variables
RED='\[\e[1;31m\]'
GREEN='\[\e[1;32m\]'
DARK_GREEN='\[\e[0;32m\]'
BLUE='\[\e[1;34m\]'
CYAN='\[\e[1;36m\]'
WHITE='\[\e[1;37m\]'
NORM='\[\e[m\]'

# Box printing shortcut variables
BOX_TOPL='\342\224\214'
BOX_BOTL='\342\224\224'
BOX_HORIZ='\342\224\200'

# }}}

echo "${WHITE}${BOX_TOPL}[${CYAN}\u@${CYAN}\h${WHITE}]\
${BOX_HORIZ}(${GREEN}\w${GIT_BRANCH}${WHITE})\
${BOX_HORIZ}(${BLUE}$(date "${DATE_SEQ}")${WHITE})\
${BOX_HORIZ}[${RED}${RET}${WHITE}]\
\n "

# vim: foldmethod=marker foldmarker={{{,}}}
