#!/bin/sh

# Config {{{

# Save the return value of the last command
RET="$1"

# Update path to include folder with necessary prompt scripts
# NOTE: This doesn't update the path outside this script
PATH="$PATH:$PROMPT_BASE_DIR/bin"

# Block colors
USER_COLOR="$COLOR_CYAN"
HOST_COLOR="$COLOR_DARK_CYAN"
DIRECTORY_COLOR="$COLOR_GREEN"
RETURN_STATUS_COLOR="$COLOR_RED"
PROMPT_COLOR="$COLOR_WHITE"

# Get git info for my prompt
eval "$(git_prompt.sh)"

# Switch theme if in git dir
if [ -n "$GIT_PROMPT_STATUS" ]; then
	"$PROMPT_THEME_DIR/unicode" "$1";
	exit;
fi

# }}}

# Prompt variables {{{

# Return status block, only if the value exists and is non-zero
if [ -n "$RET" ] && [ "$RET" != "0" ]; then
	RETURN_STATUS_BLOCK=" ${RETURN_STATUS_COLOR}${RET}"
fi

# }}}

echo "${USER_COLOR}\u ${HOST_COLOR}\h ${DIRECTORY_COLOR}\w\n\
${RETURN_STATUS_BLOCK} ${PROMPT_COLOR}\$ ${COLOR_NORM}"

# vim: foldmethod=marker foldmarker={{{,}}}
