#!/bin/sh

# Config {{{

# Update path to include folder with necessary prompt scripts
# NOTE: This doesn't update the path outside this script
PATH="$PATH:$PTHEME_BASE_DIR/bin"

# Block colors
DIRECTORY_COLOR="$COLOR_GREEN"
RETURN_STATUS_COLOR="$COLOR_RED"
PROMPT_COLOR="$COLOR_WHITE"

# }}}

# Shortcut variables {{{

# Unicode
PARTIAL_DIFF='\xE2\x88\x82'
EMPTY_SET='\xE2\x88\x85'
INCREMENT='\xE2\x88\x86'
THEREFORE='\xE2\x88\xB4'
LAMBDA='\xCE\xBB'
TSU='\xE3\x83\x84'
BALLOT_X='\xE2\x9C\x98'
HEAVY_RARR='\xE2\x9E\x94'

# }}}

# Prompt variables {{{

# Get info for git prompt
eval "$(git_prompt.sh -b -c)"
if [ -n "$GIT_PROMPT_STATUS" ]; then
	GIT_BLOCK=" \[${GIT_PROMPT_COLOR}\]${GIT_PROMPT_BRANCH}"
fi

# Directory and git status
DIRECTORY_BLOCK="${DIRECTORY_COLOR}\w${GIT_BLOCK}"

# Return status block, only if the value is non-zero
if [ "$RETURN_STATUS" != "0" ]; then
	RETURN_STATUS_BLOCK=" ${RETURN_STATUS_COLOR}${RETURN_STATUS}"
fi

# Prompt character block
PROMPT_BLOCK="${PROMPT_COLOR}${LAMBDA}"

# }}}

# Printf is needed because of the unicode character, it's more portable than
# echo -e
printf "${DIRECTORY_BLOCK}${COLOR_NORM}\n\
${RETURN_STATUS_BLOCK} ${PROMPT_BLOCK} ${COLOR_NORM}"

# vim: foldmethod=marker foldmarker={{{,}}}
